import getAllAuctions from "@/api/allAuctions";
import getEthPrice from "@/api/ethPrice";
import getPopularAuctions from "@/api/popularAuctions";
import AllAuctions from "@/components/AllAuctions/AllAuctions";
import Footer from "@/components/Footer";
import NavigationMenu from "@/components/Header/NavigationMenu";
import PopularAuctions from "@/components/PopularAuctions/PopularAuctions";
import { allAuctionsActions } from "@/store";
import { dm_sans } from "@/styles/fonts";
import {
  ApiResponse,
  AuctionsApiResponse,
  EthPriceApiResponse,
} from "@/types/api";
import Head from "next/head";
import { useDispatch } from "react-redux";

interface HomeProps {
  ethPrice: ApiResponse<EthPriceApiResponse>;
  popularAuctions: ApiResponse<AuctionsApiResponse>;
  allAuctions: ApiResponse<AuctionsApiResponse>;
}
export default function Home({
  ethPrice,
  popularAuctions,
  allAuctions,
}: HomeProps) {
  const dispatch = useDispatch();
  const errorMessage =
    ethPrice.errorMessage ||
    popularAuctions.errorMessage ||
    allAuctions.errorMessage;

  if (
    errorMessage ||
    !ethPrice.data ||
    !popularAuctions.data ||
    !allAuctions.data
  ) {
    return (
      <div>
        <p>Failed to load data</p>
        <p>{errorMessage}</p>
      </div>
    );
  }
    dispatch(allAuctionsActions.setAllAuctions(allAuctions.data));
  return (
    <>
      <Head>
        <title>NFPaisanos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`min-h-screen bg-black px-8 text-sm md:px-20 xl:px-40 ${dm_sans.className} font-bold`}
      >
        <NavigationMenu />
        <PopularAuctions
          ethPrice={ethPrice.data}
          auctions={popularAuctions.data}
        />
        <AllAuctions />
      </main>
      <Footer />
    </>
  );
}

export const getServerSideProps = async () => {
  const ethPrice = await getEthPrice();
  const popularAuctions = await getPopularAuctions();
  const allAuctions = await getAllAuctions();

  return {
    props: { ethPrice, popularAuctions, allAuctions },
  };
};
